scrape_configs:
  # - job_name: 'demo'
  #   metrics_path: '/actuator/prometheus'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['host.docker.internal:10001']
  # - job_name: 'app1-core'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['host.docker.internal:8400']      
  # - job_name: 'app-core-calc'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['app-calculo-core:8000']
  #     - targets: ['app1-calculo-core:8000']      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # - job_name: 'otel-collector'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['otelcol:8889']
  #     - targets: ['otelcol:8888']
  - job_name: 'app-granian'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app-granian:8000']
  - job_name: 'webflux-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['webflux-app:8080']      
  - job_name: 'app-fastify'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app-fastify:3000']