scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'app-granian'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app-granian:8000']
  - job_name: 'webflux-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['webflux-app:8080']      
  - job_name: 'app-fastify'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app-fastify:3000']
  - job_name: 'pm2'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app-fastify:9209']
      